### ISSUE TITLE
Adding song to chords list

### ISSUE THREAD

**Issue by statox** [statox/blog#105]
**This should work only if you are me**

Use this issue to add entries to [my chord page](https://www.statox.fr/chords/). Add a new comment with the following format:

    Name of the artist
    Title of the song
    url of the chords

When I add new comment to this issue, the "[Add song chords](https://github.com/statox/blog/actions/workflows/song-chords-comment.yml)" workflow is triggered, it parses the last comment, turns it into a JSON string, adds it to the list in the repo and commits the change. Then the "[deploy](https://github.com/statox/blog/actions/workflows/deploy.yml)" workflow is triggered to publish the updated list.

World's shittiest CMS yay! :tada:

**Comment by statox** [comment]
Test 1

**Comment by statox** [comment]
Test 2

**Comment by statox** [comment]
Test 3

**Comment by statox** [comment]
Test 4

**Comment by statox** [comment]
Test5

**Comment by statox** [comment]
Test 6

**Comment by statox** [comment]
Test 7

**Comment by statox** [comment]
Test 8

**Comment by statox** [comment]
Test 9

**Comment by statox** [comment]
Test 10

**Comment by statox** [comment]
Test 11

**Comment by statox** [comment]
Test 12

**Comment by statox** [comment]
Test 13

**Comment by statox** [comment]
Test 14

**Comment by statox** [comment]
Test 15

**Comment by statox** [comment]
TEst 16

**Comment by statox** [comment]
Test 17

**Comment by statox** [comment]
Test 18

**Comment by statox** [comment]
Test 19

**Comment by statox** [comment]
Test 20

**Comment by statox** [comment]
Test 21

**Comment by statox** [comment]
Test 22

**Comment by statox** [comment]
Test 
23
end

**Comment by statox** [comment]
Test 24

**Comment by statox** [comment]
Test 25

**Comment by statox** [comment]
Test 26

**Comment by statox** [comment]
Test 27

**Comment by statox** [comment]
Test
multi
lines several words

**Comment by statox** [comment]
An artiste
A title (with other characters)
https://github.com/statox/blog/issues/105

**Comment by statox** [comment]
An artist
A new tutle (with brackets)
https://github.com/statox/blog/issues/105

**Comment by statox** [comment]
An artist
A new tutle (with brackets)
#105

**Comment by statox** [comment]
Dropkick Murphys
Rose tattoo
https://www.tabs4acoustic.com/en/guitar-tabs/dropkick-murphys-tabs/rose-tattoo-acoustic-tab-389.html

**Comment by statox** [comment]
Dropkick Murphys
Rose tattoo
https://www.tabs4acoustic.com/en/guitar-tabs/dropkick-murphys-tabs/rose-tattoo-acoustic-tab-389.html

**Comment by statox** [comment]
Dropkick Murphys
Rose tattoo
https://www.tabs4acoustic.com/en/guitar-tabs/dropkick-murphys-tabs/rose-tattoo-acoustic-tab-389.html

**Comment by statox** [comment]
Joe Dassin
A toi
https://tabs.ultimate-guitar.com/tab/1182958

**Comment by statox** [comment]
Joe Dassin
A toi
https://tabs.ultimate-guitar.com/tab/1182958

**Comment by statox** [comment]
Joe Dassin
A toi
https://tabs.ultimate-guitar.com/tab/1182958

**Comment by statox** [comment]
Joe Dassin
A toi
https://tabs.ultimate-guitar.com/tab/1182958

**Comment by statox** [comment]
Joe Dassin
A toi
https://tabs.ultimate-guitar.com/tab/1182958

**Comment by statox** [comment]
The rolling stones
Prodigal son
https://www.boiteachansons.net/Partitions/The-Rolling-Stones/Prodigal-Son.php

**Comment by statox** [comment]
The Beach Boys
Surfin' USA
https://www.boiteachansons.net/Partitions/The-Beach-Boys/Surfin-USA.php

**Comment by statox** [comment]
Renaud
L'auto stoppeuse
https://www.boiteachansons.net/Partitions/Renaud/L-auto-stoppeuse.php

**Comment by statox** [comment]
Renaud
L'auto stoppeuse
https://www.boiteachansons.net/Partitions/Renaud/L-auto-stoppeuse.php

**Comment by statox** [comment]
Broken comment should not trigger deploy workflow

**Comment by statox** [comment]
Broken comment should not trigger deploy workflow for real this time

**Comment by statox** [comment]
Broken comment should not trigger deploy workflow. Third time's a Charm or whatever

**Comment by BadaBoum13** [comment]
Forbidden artist
Forbidden title
This shouldn't have been published

**Comment by statox** [comment]
Thoinot Arbeau
Belle qui tiens ma vie
https://www.partitions-domaine-public.fr/telechargement_pdf.php?id=18390

**Comment by statox** [comment]
Traditional
Il pleut bergère
https://s3.eu-west-3.amazonaws.com/chordsstorage.statox.fr/Traditionnel_-_Il_pleut_bergere.pdf

**Comment by statox** [comment]
Kenny Rogers
The Gambler
https://tabs.ultimate-guitar.com/tab/kenny-rogers/the-gambler-chords-627779

**Comment by statox** [comment]
Traditional
L’espérance
https://tabs.ultimate-guitar.com/tab/3782615

**Comment by statox** [comment]
Serge Gainsbourg
La javanaise
https://tabs.ultimate-guitar.com/tab/serge-gainsbourg/la-javanaise-chords-1130236

**Comment by statox** [comment]
The last of us
Main theme
https://tabs.ultimate-guitar.com/tab/misc-computer-games/the-last-of-us-main-theme-tabs-1828201

**Comment by statox** [comment]
Scorpion
The wind of change
https://tabs.ultimate-guitar.com/tab/scorpions/wind-of-change-chords-102896

**Comment by statox** [comment]
BB King
The thrill is gone
https://tabs.ultimate-guitar.com/tab/b-b-king/the-thrill-is-gone-chords-712526

**Comment by statox** [comment]
Aladdin - Disney
Prince Ali
https://tabs.ultimate-guitar.com/tab/misc-cartoons/aladdin-prince-ali-chords-1721150

**Comment by statox** [comment]
Eddy Mitchell
Pas De Boogie Woogie
https://tabs.ultimate-guitar.com/tab/eddy-mitchell/pas-de-boogie-woogie-chords-1705923

**Comment by statox** [comment]
Bobby McFerrin
Don’t worry be happy
https://tabs.ultimate-guitar.com/tab/bobby-mcferrin/dont-worry-be-happy-chords-484289

**Comment by statox** [comment]
The Pogues
I’m a man you don’t meet everyday
https://tabs.ultimate-guitar.com/tab/pogues/im-a-man-you-dont-meet-every-day-chords-80099

**Comment by statox** [comment]
The Pogues
Sally Mclennane
https://tabs.ultimate-guitar.com/tab/pogues/sally-mclennane-chords-80208

**Comment by statox** [comment]
Hugues Aufray
Stewball
https://tabs.ultimate-guitar.com/tab/hugues-aufray/stewball-chords-1875800

**Comment by statox** [comment]
Peter, Paul and Mary
Stewball
https://tabs.ultimate-guitar.com/tab/peter-paul-and-mary/stewball-chords-1053319

**Comment by statox** [comment]
John Prine
In Spite Of Ourselves
https://tabs.ultimate-guitar.com/tab/john-prine/in-spite-of-ourselves-chords-1872988

**Comment by statox** [comment]
San Tropez
Pink Floyd
https://tabs.ultimate-guitar.com/tab/pink-floyd/san-tropez-chords-43468

**Comment by statox** [comment]
Scorpion
Still loving you
https://tabs.ultimate-guitar.com/tab/scorpions/still-loving-you-chords-1088579

**Comment by statox** [comment]
Kenny Rogers
Just Dropped In (To See What Condition My Condition Was In)
https://tabs.ultimate-guitar.com/tab/kenny-rogers-and-the-first-edition/just-dropped-in-to-see-what-condition-my-condition-was-in-chords-1757925

**Comment by statox** [comment]
Fats domino
Blueberry hill
https://tabs.ultimate-guitar.com/tab/fats-domino/blueberry-hill-chords-1086974

**Comment by statox** [comment]
The Carpenters
Top of the world
https://tabs.ultimate-guitar.com/tab/carpenters/top-of-the-world-chords-1433710

**Comment by statox** [comment]
Simon and Garfunkel
The Sound Of Silence
https://tabs.ultimate-guitar.com/tab/simon-garfunkel/the-sound-of-silence-chords-159157

**Comment by statox** [comment]
The Carpenters
Close To You
https://tabs.ultimate-guitar.com/tab/carpenters/close-to-you-chords-1044073

**Comment by statox** [comment]
The Carpenters
Please Mister Postman
https://tabs.ultimate-guitar.com/tab/the-beatles/please-mister-postman-chords-17342

**Comment by statox** [comment]
Eric Clapton
Layla
https://tontonremy.com/ukulele/partoches/english/uk/page649/page160/page160.html

**Comment by statox** [comment]
Les VRP
Ramon Perez
https://tabs.ultimate-guitar.com/tab/les-vrp/ramon-perez-chords-3385475

**Comment by statox** [comment]
The Animals
Don't let me be misunderstood
https://tabs.ultimate-guitar.com/tab/the-animals/dont-let-me-be-misunderstood-chords-18691

**Comment by statox** [comment]
Gorillaz
Clint Eastwood

**Comment by statox** [comment]
Gorillaz
Clint Eastwood
https://tabs.ultimate-guitar.com/tab/gorillaz/clint-eastwood-chords-1177624

**Comment by statox** [comment]
Test1
A first test
https://url.url
tag1, tag2 , tag3,tag4,tag5

**Comment by statox** [comment]
Test2
A second test
https://url.url

**Comment by statox** [comment]
Test2
A second test
https://url.url

**Comment by statox** [comment]
Test3
Another test
http://test

**Comment by statox** [comment]
Liquido
Narcotic
https://tabs.ultimate-guitar.com/tab/liquido/narcotic-chords-924106
english,pop

**Comment by statox** [comment]
M
Mama Sam
https://tabs.ultimate-guitar.com/tab/matthieu-chedid/mama-sam-chords-1173332
french,group

**Comment by statox** [comment]
Liquido
Narcotic - tabs
https://tabs.ultimate-guitar.com/tab/liquido/narcotic-tabs-9735
 english,pop

**Comment by statox** [comment]
Liquido
Narcotic - bass
https://www.bigbasstabs.com/liquido_bass_tabs/narcotic_ver_2.html
english,pop

**Comment by statox** [comment]
Liquido
Narcotic - song structure
http://stiff-cloud.quickconnect.to/d/s/oI80TVUrsV2fLU1hL0IplyIM8HKEuhtu/mw-9raDkvxtJFyl4LEdJLEpSGR7ZAazc-cbZgy4m7cgk
english,pop

**Comment by statox** [comment]
Agnes Obel
Riverside
https://tabs.ultimate-guitar.com/tab/agnes-obel/riverside-chords-1028711

**Comment by statox** [comment]
Ed Sheeran
Shape of you
https://tabs.ultimate-guitar.com/tab/ed-sheeran/shape-of-you-chords-1928439

**Comment by statox** [comment]
Khaled
Aicha
https://tabs.ultimate-guitar.com/tab/1962471

**Comment by statox** [comment]
Stray cats
Stray cat strut
https://tabs.ultimate-guitar.com/tab/stray-cats/stray-cat-strut-chords-84091

**Comment by statox** [comment]
John Lennon
Imagine
https://tabs.ultimate-guitar.com/tab/john-lennon/imagine-chords-9306

**Comment by statox** [comment]
Smash Mouth
All Star (Shrek theme)
https://tabs.ultimate-guitar.com/tab/smash-mouth/all-star-chords-428803

**Comment by statox** [comment]
Blink 182
What's my age again?
https://tabs.ultimate-guitar.com/tab/blink-182/whats-my-age-again-chords-1173080

**Comment by statox** [comment]
Lana Del Rey
Summertime sadness
https://tabs.ultimate-guitar.com/tab/lana-del-rey/summertime-sadness-chords-1129189

**Comment by statox** [comment]
No doubt
Don't speak
https://tabs.ultimate-guitar.com/tab/no-doubt/dont-speak-chords-850875

**Comment by statox** [comment]
Green Day
Boulevard of broken dreams
https://tabs.ultimate-guitar.com/tab/green-day/boulevard-of-broken-dreams-chords-146744
slow,simple,english

**Comment by statox** [comment]
Aretha Franklin
Say a little prayer
https://tabs.ultimate-guitar.com/tab/aretha-franklin/i-say-a-little-prayer-chords-276769
slow,english

**Comment by statox** [comment]
The Beatles
Hey Jude
https://tabs.ultimate-guitar.com/tab/the-beatles/hey-jude-chords-1061739
english

**Comment by statox** [comment]
Wind Rose
Diggy diggy hole
https://tabs.ultimate-guitar.com/tab/the-yogscast/diggy-diggy-hole-chords-1514572
group,english

**Comment by statox** [comment]
Sublime
Santeria
https://tabs.ultimate-guitar.com/tab/sublime/santeria-chords-521535
english,slow

**Comment by statox** [comment]
Elvis Presley
Hound dog
https://tabs.ultimate-guitar.com/tab/elvis-presley/hound-dog-chords-346314
blues,english

**Comment by statox** [comment]
David Allan Coe
Piece of wood and steel
https://tabs.ultimate-guitar.com/tab/david-allan-coe/piece-of-wood-and-steel-chords-1945807
country,slow,english

**Comment by statox** [comment]
Willie Nelson
Whiskey river
https://tabs.ultimate-guitar.com/tab/willie-nelson/whiskey-river-chords-1498003
country,slow,english

**Comment by statox** [comment]
Jarabe Tapatio (Mexican Hat Dance)
Traditional
https://tabs.ultimate-guitar.com/tab/misc-traditional/mexican-hat-dance-tabs-645442

**Comment by statox** [comment]
Aqua
Barbie girl
https://tabs.ultimate-guitar.com/tab/aqua/barbie-girl-chords-354593

**Comment by statox** [comment]
Green Day
American idiot
https://tabs.ultimate-guitar.com/tab/green-day/american-idiot-chords-145586

**Comment by statox** [comment]
Traditional
Amazing grace
https://tabs.ultimate-guitar.com/tab/misc-praise-songs/amazing-grace-chords-614298

**Comment by statox** [comment]
The Pixies
Where is my mind
https://tabs.ultimate-guitar.com/tab/pixies/where-is-my-mind-chords-89446

**Comment by statox** [comment]
Meghan Trainor
All about that bass
https://tabs.ultimate-guitar.com/tab/meghan-trainor/all-about-that-bass-chords-1494750

**Comment by statox** [comment]
Carlos Santana
Europa
https://www.songsterr.com/a/wsa/carlos-santana-europa-tab-s451

**Comment by statox** [comment]
The Ventures
Walk don't run
https://www.songsterr.com/a/wsa/ventures-walk-dont-run-tab-s23896

**Comment by statox** [comment]
The Allman Brothers Band
Jessica (tab)
https://www.guitaretab.com/t/the-allman-brothers-band/122493.html

**Comment by statox** [comment]
Alela Diane
The pirates gospel
https://tabs.ultimate-guitar.com/tab/alela-diane/the-pirates-gospel-tabs-703620

**Comment by statox** [comment]
Alela Diane
The pirates gospel
https://tabs.ultimate-guitar.com/tab/alela-diane/the-pirates-gospel-tabs-703620

**Comment by statox** [comment]
Alela Diane
The pirates gospel
https://tabs.ultimate-guitar.com/tab/alela-diane/the-pirates-gospel-tabs-703620

**Comment by statox** [comment]
Willie Nelson
Blue skies
https://tabs.ultimate-guitar.com/tab/willie-nelson/blue-skies-chords-1505954

**Comment by statox** [comment]
The Grateful Dead
Ripple
https://www.youtube.com/watch?v=HmXcOCWJ2n8

**Comment by statox** [comment]
Traditional
Molly Malone
https://tabs.ultimate-guitar.com/tab/misc-traditional/molly-malone-chords-816941

**Comment by statox** [comment]
Traditional
Wiskey in the jar
https://tabs.ultimate-guitar.com/tab/the-dubliners/whiskey-in-the-jar-chords-764863

**Comment by statox** [comment]
The Pogues
Dirty old town
https://tabs.ultimate-guitar.com/tab/the-pogues/dirty-old-town-chords-814642

**Comment by statox** [comment]
Bob Dylan
Don’t think twice it’s alright 
https://tabs.ultimate-guitar.com/tab/bob-dylan/dont-think-twice-its-all-right-chords-178850

**Comment by statox** [comment]
Les Béruriers Noirs
L'empereur Tomato Ketchup
https://tabs.ultimate-guitar.com/tab/3904292

**Comment by statox** [comment]
Ska P
El vals del obrero
https://es.ultimate-guitar.com/tab/ska-p/el-vals-del-obrero-somos-la-revolucion-chords-2980427

**Comment by statox** [comment]
Traditional
I'll fly away
https://tabs.ultimate-guitar.com/tab/albert-e-brumley/ill-fly-away-chords-815083

**Comment by statox** [comment]
The dead south
In hell I'll be in good company
https://tabs.ultimate-guitar.com/tab/the-dead-south/in-hell-ill-be-in-good-company-chords-1952761

**Comment by statox** [comment]
Flogging Molly
If I ever leave this world alive
https://tabs.ultimate-guitar.com/tab/flogging-molly/if-i-ever-leave-this-world-alive-chords-55063

**Comment by statox** [comment]
Flogging Molly
Cruel Mistress
https://tabs.ultimate-guitar.com/tab/flogging-molly/cruel-mistress-chords-187556

**Comment by statox** [comment]
Flogging Molly
Drunken lullabies
https://tabs.ultimate-guitar.com/tab/flogging-molly/drunken-lullabies-chords-484194

**Comment by statox** [comment]
Georges Moustaki
Ma liberté
https://tabs.ultimate-guitar.com/tab/1171040

**Comment by statox** [comment]
Loudon Wainwright III
The swimming song
https://tabs.ultimate-guitar.com/tab/loudon-wainwright-iii/the-swimming-song-chords-702279

**Comment by statox** [comment]
Michel Polnareff
On ira tous au paradis
https://tabs.ultimate-guitar.com/tab/michel-polnareff/on-ira-tous-au-paradis-chords-1733898

**Comment by statox** [comment]
Robin des bois - Disney
Oh de lally - Quel beau jour
https://tabs.ultimate-guitar.com/tab/misc-cartoons/robin-des-bois-quel-beau-jour-vraiment-chords-1698447

**Comment by statox** [comment]
Herman's hermits
Henry the 8th
https://tabs.ultimate-guitar.com/tab/hermans-hermits/im-henry-viii-i-am-chords-1047358

**Comment by statox** [comment]
Traditional 
El Paso del Ebro
https://tabs.ultimate-guitar.com/tab/2517126

**Comment by statox** [comment]
Creedence clearwater revival
Travelin band
https://tabs.ultimate-guitar.com/tab/creedence-clearwater-revival/travelin-band-chords-1055219

**Comment by statox** [comment]
Crosby, Stills, Nash & Young
Teach your children
https://tabs.ultimate-guitar.com/tab/crosby-stills-nash-young/teach-your-children-chords-1053633

**Comment by statox** [comment]
Blondie
One way or another
https://tabs.ultimate-guitar.com/tab/blondie/one-way-or-another-chords-467678
rock,fast

**Comment by statox** [comment]
Test
Broken link
https://broken.link.com/failing

**Comment by statox** [comment]
Test
Broken link 2
https://broken.link.com/failing2

**Comment by statox** [comment]
Talking heads
Psycho killer
https://tabs.ultimate-guitar.com/tab/talking-heads/psycho-killer-chords-435224

**Comment by statox** [comment]
Rodriguez
Sugar man
https://tabs.ultimate-guitar.com/tab/rodriguez/sugar-man-chords-811245

**Comment by statox** [comment]
Leonard Cohen
Suzanne
https://tabs.ultimate-guitar.com/tab/leonard-cohen/suzanne-chords-29753

**Comment by statox** [comment]
Dire Straits
Where do you think you’re going? (Tabs)
https://tabs.ultimate-guitar.com/tab/dire-straits/where-do-you-think-youre-going-tabs-681021
slow,Andalusian_cadence

**Comment by statox** [comment]
Strawbs
Part of the union
https://tabs.ultimate-guitar.com/tab/strawbs/part-of-the-union-chords-1489944
happy,loud

**Comment by statox** [comment]
The Statler Brothers
Flowers On The Wall Chords
https://tabs.ultimate-guitar.com/tab/the-statler-brothers/flowers-on-the-wall-chords-913105
happy,quick,country

**Comment by statox** [comment]
Wendy Rene
After Laughter
https://tabs.ultimate-guitar.com/tab/wendy-rene/after-laughter-chords-1746557
slow,reggae,vocal,sad

**Comment by statox** [comment]
Georges Brassens
Les passantes (chords)
https://tabs.ultimate-guitar.com/tab/georges-brassens/les-passantes-chords-1429512
slow,chill,romantic

**Comment by statox** [comment]
Georges Brassens
Les passantes (tabs)
https://www.songsterr.com/a/wsa/georges-brassens-les-passantes-tab-s3388t2
slow,chill,romantic

**Comment by statox** [comment]
This issue is no longer needed as I can now edit the list of my chords via my new [songbook app](https://apps.statox.fr/songbook)
